@startuml
!include <C4/C4_Context>

AddRelTag("invisible", $textColor="transparent", $lineColor="transparent", $lineStyle = DashedLine())

header Template Project
title C4 System Context Diagram Template

'----------------------------------------------------------------
'Actors
'----------------------------------------------------------------
Person(customer, "Personal Baking Customer", "A customer of the bank with one or more personal bank accounts",$type="Person")

'----------------------------------------------------------------
'Systems
'----------------------------------------------------------------
System(internet, "Internet Banking System", "Allows customers to view information about their bank accounts and make payments via the Web", $type="Software System")
System(aws, "Amazon Web Services Simple Email Service", "Cloud-based email service provider", $type="Software System")
System(core, "Core Banking System", "Handles core banking functions including customer information, bank account management, transactions, etc...", $type="Software System")

'----------------------------------------------------------------
'Relations
'----------------------------------------------------------------
Rel_D(customer, internet, "Views account balances and makes payments using")
Rel_R(internet, aws, "Views account balances and makes payments using")
Rel_R(internet, core, "Views account balances and makes payments using")
Rel_U(aws, customer, "Views account balances and makes payments using")

'----------------------------------------------------------------
'Layout
'----------------------------------------------------------------
Rel_D(aws, core, "This rel is just to compose the layout", $tags="invisible")

SHOW_LEGEND()

@enduml
